'use strict';

/**
 * Foundry's product contract.
 *
 * This is deliberately a compact declaration of business capabilities and
 * route families, not a second route table. Express remains responsible for
 * declaring concrete URLs. At boot the product brain reads the real routers,
 * expands every route, and requires each one to match one of these families.
 * A new route therefore participates automatically when it belongs to an
 * existing capability; a new product area cannot ship until its capability
 * and access contract are declared here.
 */
const P = require('../actions/permissions');
const removals = require('../actions/removals');

const capabilities = [
  { id: 'workspace.manage', label: 'Workspaces', status: 'available', permission: P.ADMIN,
    description: 'Create, choose, recover, export or delete a workspace.', destination: 'workspaces' },
  { id: 'onboarding.manage', label: 'Inventory setup', status: 'available', permission: P.ADMIN,
    description: 'Understand the business, bring in real records and configure safe inventory structure.', destination: 'onboarding' },
  { id: 'inventory.view', label: 'Inventory', status: 'available', permission: P.VIEW,
    description: 'See products, variants, units, batches, locations and current quantities.', destination: 'inventory' },
  { id: 'inventory.record-movement', label: 'Inventory movements', status: 'available', permission: P.OPERATE,
    actionTypes: ['receive', 'issue', 'transfer', 'adjust'],
    authorityCapability: 'inventory_transfers',
    description: 'Record or propose receipts, sales/issues, transfers, counts/corrections, locations, products or variants.', destination: 'inventory',
    manager: { intentClass: 'INVENTORY_ACTION', handler: 'inventory_action', examples: ['stock arrived', 'we sold some units', 'move stock', 'correct this count', 'add a product'], safety: 'All consequential changes use the action preview and inventory engine.' } },
  { id: 'inventory.manage-transfers', label: 'Inventory transfers', status: 'available', permission: P.VIEW_TRANSFERS,
    actionPermission: P.REQUEST_TRANSFER, authorityCapability: 'inventory_transfers',
    actionTypes: ['request_transfer','approve_transfer','pick_transfer','dispatch_transfer','receive_transfer'],
    description: 'Request, approve, pick, dispatch, track and receive stock between locations with explicit in-transit custody and variance handling.',
    destination: 'transfers', prerequisites: ['A real source, destination and product identity are required.'],
    manager: { intentClass: 'INVENTORY_ACTION', handler: 'inventory_action', examples: ['transfer 12 to the downtown store', 'what is in transit', 'receive transfer TR-0001'], safety: 'Dispatch and receipt are separate inventory-engine movements; retries cannot post either leg twice.' } },
  { id: 'catalog.transform-internal-codes', label: 'Product code changes', status: 'available', permission: P.OPERATE,
    description: 'Change customer-owned product or SKU identifiers with collision checks and preview.', destination: 'inventory',
    manager: { intentClass: 'CATALOG_CHANGE', handler: 'catalog_code_change', examples: ['change a code prefix'], safety: 'Previews every affected code and requires approval.' } },
  { id: 'catalog.remove-imported-records', label: 'Imported record rollback', status: 'available', permission: P.ADMIN,
    description: 'Roll back records created by an applied source while preserving provenance.', destination: 'imports',
    manager: { intentClass: 'CATALOG_CHANGE', handler: 'document_removal', examples: ['undo products from the last file'], safety: 'Previews provenance and quantities and preserves the audit trail.' } },
  { id: 'catalog.manage', label: 'Product catalogue', status: 'available', permission: P.OPERATE,
    actionTypes: ['create_item', 'configure_kit', 'archive_item', 'add_location', 'rename_terminology'],
    description: 'Create, archive or change products, variants, sellable kit/BOM component definitions, locations and customer terminology.', destination: 'inventory',
    manager: { intentClass: 'CATALOG_CHANGE', handler: 'inventory_action', examples: ['add another warehouse', 'create a size variant', 'make this SKU a kit containing these component SKUs'], safety: 'Uses a grounded preview before changing catalogue records or kit definitions.' } },
  { id: 'records.remove', label: 'Removing records', status: 'available', permission: P.VIEW,
    actionTypes: [removals.ACTION_TYPE],
    description: `Retire ${removals.labelList()} that is no longer used, `
      + 'deleting it when nothing refers to it and archiving it when something does.',
    destination: 'settings',
    // Authority follows the record, not the verb: suppliers answer to the
    // supplier grant, locations to administration. The check that matters runs
    // in permissions.js with the actual record in hand.
    prerequisites: [`Which permission is needed depends on the kind of record: `
      + removals.KINDS.map((k) => `${k.plural} need ${k.permission}`).join(', ') + '.'],
    sideEffects: ['Deletes the record outright only when nothing refers to it; otherwise hides it and keeps it.',
      'Never changes a stock count, and refuses while an order against the record is still open.'],
    manager: { intentClass: 'CONFIGURATION_CHANGE', handler: 'inventory_action',
      examples: removals.KINDS.map((k) => k.says[0]),
      safety: 'Shows which of deletion or archiving will happen, and what is holding the record, before approval.' } },
  { id: 'purchasing.manage', label: 'Purchasing', status: 'available', permission: P.VIEW_PURCHASING,
    actionTypes: ['purchase', 'receive_shipment'],
    actionPermission: P.CREATE_PO, authorityCapability: 'replenishment',
    description: 'Plan replenishment, manage suppliers and purchase orders, and receive deliveries.', destination: 'purchasing',
    manager: { intentClass: 'PURCHASING_REQUEST', handler: 'purchasing', examples: ['order what is needed', 'receive PO-1001'], safety: 'Supplier rules and authority gates remain deterministic.' } },
  { id: 'supplier.map-code', label: 'Supplier product mapping', status: 'available', permission: P.MANAGE_SUPPLIERS,
    description: 'Map a supplier product code to an internal product.', destination: 'suppliers',
    manager: { intentClass: 'CONFIGURATION_CHANGE', handler: 'supplier_code_mapping', examples: ['their code V-10 is our TS-10'], safety: 'Shows both records before approval.' } },
  { id: 'sales.manage-orders', label: 'Customer orders', status: 'available', permission: P.VIEW_SALES,
    actionTypes: ['sales_order', 'fulfill_sales_order'],
    actionPermission: P.MANAGE_SALES, description: 'Create, change, commit, fulfill, cancel and inspect customer orders.', destination: 'sales',
    manager: { intentClass: 'SALES_ORDER', handler: 'sales_order', examples: ['a customer ordered 40', 'ship 20', 'what is backordered'], safety: 'Commitments never impersonate physical movements.' } },
  { id: 'pricing.manage', label: 'Selling prices', status: 'available', permission: P.VIEW,
    actionPermission: P.OPERATE, description: 'Review, set and approve evidence-backed selling prices.', destination: 'inventory' },
  { id: 'accounting.manage', label: 'Accounting', status: 'available', permission: P.VIEW_ACCOUNTING,
    actionPermission: P.MANAGE_ACCOUNTING, description: 'Track evidence-backed bills, payments, expenses, inventory value, sales, profit and cash.', destination: 'accounting' },
  { id: 'accounting.record-inventory-cost', label: 'Current purchase cost', status: 'available', permission: P.VIEW,
    actionPermission: P.ADMIN,
    description: 'Record the current price paid per inventory unit, use it in purchasing and margin decisions, and keep historical inventory valuation separate.', destination: 'inventory',
    manager: { intentClass: 'CONFIGURATION_CHANGE', handler: 'inventory_cost_update', examples: ['set the purchase cost for my products', 'record what I pay per item'], safety: 'Shows every affected product and warns about below-cost selling before approval; it never rewrites historical COGS.' } },
  { id: 'forecasting.plan', label: 'Demand forecasting', status: 'available', permission: P.VIEW_PURCHASING,
    description: 'Use recorded demand history to forecast stock risk and explain replenishment advice.', destination: 'planning', prerequisites: ['Recorded demand history improves forecast confidence.'] },
  { id: 'learning.governed', label: 'Outcome learning', status: 'available', permission: P.VIEW_PURCHASING,
    actionPermission: P.ADMIN, destination: 'planning',
    description: 'Compare expected and actual outcomes, detect recurring bias, and propose versioned policy improvements with monitored rollout and rollback.',
    prerequisites: ['Measured outcomes are required before Foundry proposes a change.'],
    sideEffects: ['A proposal changes nothing until approved or covered by explicit narrow learning authority.',
      'Approved changes use the owning deterministic policy service and preserve the previous value for rollback.'] },
  { id: 'connections.manage', label: 'Connections', status: 'available', permission: P.ADMIN,
    description: 'Connect, map, pause, resume and troubleshoot external systems.', destination: 'connections',
    manager: { intentClass: 'CONFIGURATION_CHANGE', handler: 'connection_management', examples: ['connect Shopify', 'diagnose Square'], safety: 'Mappings are workspace scoped and external events are idempotent.' } },
  { id: 'connections.accounting-sync', label: 'Accounting integrations', status: 'available', permission: P.ADMIN,
    description: 'Connect QuickBooks or Xero read-only, verify a real company fact, shadow-reconcile exact account identities, and enable outbound posting only after parity and explicit authority.',
    destination: 'connections', prerequisites: ['Provider OAuth credentials are required.', 'Posting requires Foundry to be the declared source of truth and a matching shadow reconciliation.'] },
  { id: 'communications.manage', label: 'Business email', status: 'available', permission: P.ADMIN,
    authorityCapability: 'supplier_emails',
    description: 'Connect approved mailboxes and handle supplier or customer messages with evidence.', destination: 'mail' },
  { id: 'payments.manage', label: 'Payments', status: 'available', permission: P.VIEW_ACCOUNTING,
    actionPermission: P.RECORD_PAYMENTS, description: 'Collect and record partial or full customer payments and supplier payments.', destination: 'accounting' },
  { id: 'shipping.manage', label: 'Shipping', status: 'available', permission: P.VIEW_SALES,
    actionPermission: P.FULFILL_SALES, authorityCapability: 'shipping_labels', description: 'Set up shipping, buy labels with the business account, record tracking and update fulfillment.', destination: 'shipping', prerequisites: ['A connected shipping account, ship-from address and business payment method are required for real labels.'] },
  { id: 'rules.manage', label: 'Operating rules', status: 'available', permission: P.ADMIN,
    description: 'Manage lasting stock, supplier, replenishment, protection and authority instructions.', destination: 'autopilot',
    manager: { intentClass: 'OPERATING_INSTRUCTION', handler: 'operating_instruction', examples: ['reorder below 20', 'never spend over 500'], safety: 'Authority changes require explicit confirmation.' } },
  { id: 'events.record-physical-fact', label: 'Physical facts', status: 'available', permission: P.OPERATE,
    description: 'Record a count, delivery, damage, return, found stock or other observed fact.', destination: 'actions',
    manager: { intentClass: 'PHYSICAL_EVENT', handler: 'physical_event', examples: ['I counted 7', 'the delivery arrived damaged'], safety: 'Discrepancies never silently change inventory.' } },
  { id: 'inventory.investigate', label: 'Inventory investigations', status: 'available', permission: P.VIEW,
    description: 'Investigate and explain discrepancies using recorded evidence.', destination: 'needs-you',
    manager: { intentClass: 'INVESTIGATION_REQUEST', handler: 'investigation', examples: ['investigate this mismatch'], safety: 'Never invents a correction.' } },
  { id: 'operations.repair', label: 'Diagnose and repair inconsistencies', status: 'available', permission: P.VIEW,
    actionPermission: P.OPERATE, description: 'Report, diagnose, simulate, authorize, execute and verify governed cross-domain repairs.', destination: 'repairs',
    manager: { intentClass: 'INVESTIGATION_REQUEST', handler: 'repair_case', examples: ['fix this mismatch', 'repair the stuck job'], safety: 'Uses domain-owned adapters and cannot complete until post-repair invariants pass.' } },
  { id: 'data.import-file', label: 'Data import', status: 'available', permission: P.OPERATE,
    description: 'Read and preview spreadsheets, PDFs, documents, images and text before applying records.', destination: 'imports',
    manager: { intentClass: 'IMPORT', handler: 'attachment_required', examples: ['import this spreadsheet'], safety: 'A source is interpreted and previewed before changes.' } },
  { id: 'manager.answer', label: 'Ask Foundry', status: 'available', permission: P.VIEW,
    description: 'Answer grounded questions about the business and how to use Foundry.', destination: 'ask',
    manager: { intentClass: 'QUESTION', handler: 'ask', examples: ['where do I receive a PO', 'how many are in stock'], safety: 'Read-only unless the user explicitly asks to act.' } },
  { id: 'manager.explain', label: 'Explain decisions', status: 'available', permission: P.VIEW,
    description: 'Explain a recommendation, decision, refusal or calculation from recorded evidence.', destination: 'ask',
    manager: { intentClass: 'EXPLANATION', handler: 'ask', examples: ['why did you recommend this'], safety: 'Read-only and evidence grounded.' } },
  { id: 'manager.pause-automation', label: 'Pause automation', status: 'available', permission: P.ADMIN,
    description: 'Pause consequential automatic work immediately.', destination: 'autopilot',
    manager: { intentClass: 'STOP', handler: 'autopilot_pause', examples: ['pause automatic work'], safety: 'Reversible and never changes inventory.' } },
  { id: 'exceptions.resolve', label: 'Needs You', status: 'available', permission: P.VIEW,
    description: 'Resolve only decisions or missing evidence Foundry cannot safely settle.', destination: 'needs-you' },
  { id: 'audit.view', label: 'Activity and audit trail', status: 'available', permission: P.VIEW,
    description: 'Trace actions, evidence, actors and changes.', destination: 'activity' },
  { id: 'support.use', label: 'Support and guidance', status: 'available', permission: P.VIEW,
    description: 'Find product guidance and a monitored support path.', destination: 'support' },
  { id: 'operations.certify', label: 'Production operations', status: 'available', permission: P.ADMIN,
    description: 'Review readiness, dead letters, alerts, backups and recorded production certification evidence.', destination: 'operations' },
  { id: 'warehouse.bins', label: 'Warehouse intelligence', status: 'available', permission: P.VIEW,
    actionPermission: P.OPERATE,
    actionTypes: ['warehouse_receive', 'warehouse_putaway', 'warehouse_pick', 'warehouse_count', 'warehouse_transfer',
      'count_campaign','approve_count_variance','customer_return','inspect_customer_return','refund_customer_return',
      'supplier_return','ship_supplier_return','reconcile_supplier_return','fulfillment_wave'],
    description: 'Track hierarchical warehouse locations; execute durable receiving, putaway and transfers; run blind count campaigns, governed returns, and multi-order fulfillment waves.', destination: 'warehouse',
    prerequisites: ['Scanned locations and products need real barcode identities; Foundry never infers a scanned identity.'] },
  { id: 'costing.landed-cost', label: 'Landed cost allocation', status: 'available', permission: P.VIEW_ACCOUNTING,
    actionPermission: P.MANAGE_ACCOUNTING,
    description: 'Allocate evidenced freight, duty, insurance and handling across received inventory with deterministic rounding and accounting reconciliation.', destination: 'purchasing',
    prerequisites: ['A received purchase and evidenced charge amount are required; missing conversions or weights are never guessed.'] },
  { id: 'manufacturing.manage', label: 'Manufacturing', status: 'unavailable', permission: P.VIEW,
    description: 'Manage manufacturing work orders, production consumption and finished-goods output.', unavailableReason: 'Foundry does not currently include manufacturing work orders. Sellable kits and their component BOMs are supported separately in the product catalogue.', prerequisites: ['A manufacturing domain for production work orders must be implemented.'] },
  { id: 'edi.manage', label: 'EDI', status: 'unavailable', permission: P.ADMIN,
    description: 'Exchange structured trading documents over EDI.', unavailableReason: 'EDI connections are not implemented yet.', prerequisites: ['An approved EDI provider and document contracts are required.'] },
];

const destinations = [
  { id: 'home', label: 'Home', href: '/', capability: 'manager.answer', aliases: ['home', 'brief', 'morning briefing'] },
  { id: 'needs-you', label: 'Needs You', href: '/needs-you', capability: 'exceptions.resolve', aliases: ['needs you', 'decisions', 'exceptions'] },
  { id: 'ask', label: 'Ask Foundry', href: '/ask', capability: 'manager.answer', aliases: ['ask foundry', 'questions'] },
  { id: 'inventory', label: 'Inventory', href: '/inventory', capability: 'inventory.view', aliases: ['inventory', 'products', 'stock', 'catalog', 'catalogue'] },
  { id: 'locations', label: 'Locations', href: '/locations', capability: 'inventory.view', aliases: ['locations', 'warehouses', 'stores'] },
  { id: 'warehouse', label: 'Warehouse work', href: '/warehouse', capability: 'warehouse.bins', aliases: ['warehouse', 'bins', 'aisles', 'shelves', 'scan', 'scanning', 'putaway', 'warehouse tasks'] },
  { id: 'transfers', label: 'Transfers', href: '/transfers', capability: 'inventory.manage-transfers', aliases: ['transfers', 'stock transfers', 'inventory transfers', 'in transit'] },
  { id: 'purchasing', label: 'Purchasing', href: '/purchasing', capability: 'purchasing.manage', aliases: ['purchasing', 'purchase orders', 'POs', 'replenishment'] },
  { id: 'suppliers', label: 'Suppliers', href: '/suppliers', capability: 'purchasing.manage', aliases: ['suppliers', 'vendors'] },
  { id: 'sales', label: 'Sales orders', href: '/sales', capability: 'sales.manage-orders', aliases: ['sales', 'sales orders', 'customer orders', 'customers'] },
  { id: 'accounting', label: 'Accounting', href: '/accounting', capability: 'accounting.manage', aliases: ['accounting', 'money', 'books', 'profit'] },
  { id: 'planning', label: 'Planning and forecasts', href: '/planning', capability: 'forecasting.plan', aliases: ['planning', 'forecasting', 'forecasts', 'demand forecast'] },
  { id: 'connections', label: 'Connections', href: '/settings/connections', capability: 'connections.manage', aliases: ['connections', 'integrations', 'shopify', 'square', 'clover', 'quickbooks', 'xero', 'accounting integration', 'api', 'webhooks'] },
  { id: 'mail', label: 'Email connections', href: '/settings/connections#connection-group-email', capability: 'communications.manage', aliases: ['email', 'mailbox', 'supplier email'] },
  { id: 'shipping', label: 'Shipping setup', href: '/settings/connections#connection-group-shipping', capability: 'shipping.manage', aliases: ['shipping', 'labels', 'carrier'] },
  { id: 'autopilot', label: 'Automatic work', href: '/autopilot', capability: 'rules.manage', aliases: ['autopilot', 'automatic work', 'authority', 'rules'] },
  { id: 'imports', label: 'Imports', href: '/imports', capability: 'data.import-file', aliases: ['imports', 'upload', 'files'] },
  { id: 'actions', label: 'Record inventory activity', href: '/actions', capability: 'inventory.record-movement', aliases: ['record activity', 'receive stock', 'move stock', 'count stock'] },
  { id: 'activity', label: 'Activity', href: '/activity', capability: 'audit.view', aliases: ['activity', 'history', 'audit log'] },
  { id: 'settings', label: 'Settings', href: '/settings', capability: 'workspace.manage', aliases: ['settings', 'people', 'permissions'] },
  { id: 'workspaces', label: 'Inventories', href: '/inventories', capability: 'workspace.manage', aliases: ['workspaces', 'inventories', 'businesses'] },
  { id: 'onboarding', label: 'Set up inventory', href: '/onboarding', capability: 'onboarding.manage', aliases: ['setup', 'onboarding', 'set up inventory'] },
  { id: 'migration', label: 'Move to Foundry', href: '/onboarding/migrations/new', capability: 'onboarding.manage', aliases: ['migration', 'migrate', 'switch systems', 'move to foundry', 'import my existing inventory'] },
  { id: 'support', label: 'Support', href: '/support', capability: 'support.use', aliases: ['support', 'help', 'contact support'] },
  { id: 'repairs', label: 'Repair cases', href: '/repairs', capability: 'operations.repair', aliases: ['repairs', 'mismatches', 'fix problems'] },
  { id: 'operations', label: 'Production operations', href: '/settings/operations', capability: 'operations.certify', aliases: ['production status', 'readiness', 'dead letters', 'monitoring'] },
];

const entities = [
  { id: 'product', label: 'Product', capability: 'inventory.view', route: '/inventory/:id' },
  { id: 'variant', label: 'Variant', capability: 'inventory.view', route: '/inventory/:itemId#sku-:id' },
  { id: 'serial_unit', label: 'Serial unit', capability: 'inventory.view', route: '/inventory/:itemId#unit-:id' },
  { id: 'batch', label: 'Batch', capability: 'inventory.view', route: '/inventory/:itemId#lot-:id' },
  { id: 'location', label: 'Location', capability: 'inventory.view', route: '/locations#location-:id' },
  { id: 'warehouse_task', label: 'Warehouse task', capability: 'warehouse.bins', route: '/warehouse/tasks/:id' },
  { id: 'inventory_transfer', label: 'Inventory transfer', capability: 'inventory.manage-transfers', route: '/transfers/:id' },
  { id: 'container', label: 'Warehouse container', capability: 'warehouse.bins', route: '/warehouse#containers' },
  { id: 'supplier', label: 'Supplier', capability: 'purchasing.manage', route: '/suppliers/:id' },
  { id: 'purchase_order', label: 'Purchase order', capability: 'purchasing.manage', route: '/purchasing/orders/:id',
    contexts: [
      { id: 'receipts', label: 'Show deliveries for :title', intent: 'view',
        route: '/purchasing/orders/:id/detail#receipts',
        aliases: ['receipt', 'receipts', 'deliveries', 'received inventory', 'what arrived', 'booked deliveries'] },
      { id: 'receive', label: 'Receive :title', intent: 'action',
        route: '/purchasing/orders/:id/receive',
        aliases: ['receive', 'receiving', 'book in', 'record delivery'] },
      { id: 'supplier-bill', label: 'Show the supplier bill for :title', intent: 'view',
        route: '/accounting#supplier-:relatedId', relatedEntity: 'supplier_bill',
        aliases: ['supplier bill', 'invoice', 'what we owe'] },
      { id: 'supplier-payment', label: 'Show the supplier payment for :title', intent: 'view',
        route: '/accounting#supplier-payment-:relatedId', relatedEntity: 'supplier_bill',
        aliases: ['supplier payment', 'paid supplier', 'payment to supplier'] },
    ] },
  { id: 'supplier_bill', label: 'Supplier bill', capability: 'accounting.manage', route: '/accounting/payables' },
  { id: 'customer', label: 'Customer', capability: 'sales.manage-orders', route: '/sales/customers/:id' },
  { id: 'sales_order', label: 'Sales order', capability: 'sales.manage-orders', route: '/sales/orders/:id',
    contexts: [
      { id: 'fulfilment', label: 'Show fulfillment for :title', intent: 'view',
        route: '/orders/:id/detail?open=fulfilment#fulfilment',
        aliases: ['fulfillment', 'fulfilment', 'shipment', 'shipping', 'what left', 'delivery status'] },
      { id: 'money', label: 'Record payment for :title', intent: 'view',
        route: '/orders/:id/detail?open=money#money',
        aliases: ['payment', 'paid', 'unpaid', 'customer owes', 'invoice', 'receipt'] },
    ] },
  { id: 'fulfillment', label: 'Fulfillment', capability: 'sales.manage-orders', route: '/fulfilment/:id' },
  { id: 'payment', label: 'Payment', capability: 'payments.manage', route: '/accounting' },
  { id: 'expense', label: 'Expense', capability: 'accounting.manage', route: '/accounting/expenses' },
  { id: 'connection', label: 'Connection', capability: 'connections.manage', route: '/settings/connections/:id' },
  { id: 'exception', label: 'Needs You decision', capability: 'exceptions.resolve', route: '/needs-you' },
  { id: 'repair_case', label: 'Repair case', capability: 'operations.repair', route: '/repairs/:id' },
  { id: 'import', label: 'Import', capability: 'data.import-file', route: '/imports/:id' },
];

// Ordered most-specific first. Concrete Express routes are discovered at boot.
const routeFamilies = [
  { id: 'internal', internal: true, patterns: [/^\/(?:healthz|readyz)$/, /^\/api(?:\/|$)/, /^\/webhooks?(?:\/|$)/, /^\/shipping\/webhook(?:\/|$)/, /^\/payments\/webhook(?:\/|$)/] },
  { id: 'auth', internal: false, capability: 'workspace.manage', permission: null, patterns: [/^\/(?:login|logout|register|forgot-password|reset-password)(?:\/|$)/] },
  { id: 'workspaces', capability: 'workspace.manage', patterns: [/^\/inventories(?:\/|$)/, /^\/workspaces(?:\/|$)/] },
  { id: 'manager', capability: 'manager.answer', patterns: [/^\/foundry(?:\/|$)/, /^\/ask(?:\/|$)/, /^\/guide(?:\/|$)/] },
  { id: 'repairs', capability: 'operations.repair', patterns: [/^\/repairs(?:\/|$)/] },
  { id: 'needs-you', capability: 'exceptions.resolve', patterns: [/^\/needs-you(?:\/|$)/, /^\/attention(?:\/|$)/, /^\/investigations(?:\/|$)/, /^\/document-removals(?:\/|$)/, /^\/import-removals(?:\/|$)/, /^\/catalog-code-changes(?:\/|$)/] },
  { id: 'sales', capability: 'sales.manage-orders', patterns: [/^\/sales(?:\/|$)/, /^\/orders(?:\/|$)/, /^\/fulfilment(?:\/|$)/] },
  { id: 'pricing', capability: 'pricing.manage', patterns: [/^\/pricing(?:\/|$)/] },
  { id: 'communications', capability: 'communications.manage', patterns: [/^\/messages(?:\/|$)/, /^\/mail(?:\/|$)/, /^\/settings\/mail(?:\/|$)/] },
  { id: 'payments', capability: 'payments.manage', patterns: [/^\/payments(?:\/|$)/, /^\/settings\/connections\/payments(?:\/|$)/] },
  { id: 'shipping', capability: 'shipping.manage', patterns: [/^\/shipping(?:\/|$)/, /^\/settings\/connections\/shipping(?:\/|$)/] },
  { id: 'connections', capability: 'connections.manage', patterns: [/^\/settings\/connections(?:\/|$)/, /^\/connections(?:\/|$)/] },
  { id: 'operations', capability: 'operations.certify', patterns: [/^\/settings\/operations(?:\/|$)/] },
  { id: 'accounting', capability: 'accounting.manage', patterns: [/^\/accounting(?:\/|$)/, /^\/money(?:\/|$)/] },
  { id: 'purchasing', capability: 'purchasing.manage', patterns: [/^\/purchasing(?:\/|$)/, /^\/suppliers(?:\/|$)/, /^\/supplier-(?:code-)?mappings(?:\/|$)/] },
  { id: 'warehouse', capability: 'warehouse.bins', patterns: [/^\/warehouse(?:\/|$)/] },
  { id: 'transfers', capability: 'inventory.manage-transfers', patterns: [/^\/transfers(?:\/|$)/] },
  { id: 'planning', capability: 'forecasting.plan', patterns: [/^\/planning(?:\/|$)/] },
  { id: 'autopilot', capability: 'rules.manage', patterns: [/^\/autopilot(?:\/|$)/, /^\/operating-instructions(?:\/|$)/] },
  { id: 'onboarding', capability: 'onboarding.manage', patterns: [/^\/onboarding(?:\/|$)/] },
  { id: 'imports', capability: 'data.import-file', patterns: [/^\/imports(?:\/|$)/, /^\/what-you-told-me(?:\/|$)/] },
  { id: 'actions', capability: 'inventory.record-movement', patterns: [/^\/actions(?:\/|$)/] },
  { id: 'inventory', capability: 'inventory.view', patterns: [/^\/inventory(?:\/|$)/, /^\/locations(?:\/|$)/, /^\/search(?:\/|$)/] },
  { id: 'activity', capability: 'audit.view', patterns: [/^\/activity(?:\/|$)/] },
  { id: 'settings', capability: 'workspace.manage', patterns: [/^\/settings(?:\/|$)/] },
  { id: 'support', capability: 'support.use', patterns: [/^\/support(?:\/|$)/, /^\/everything(?:\/|$)/] },
  { id: 'home', capability: 'manager.answer', patterns: [/^\/$/, /^\/overview(?:\/|$)/] },
];

module.exports = { capabilities, destinations, entities, routeFamilies };
