ALTER TABLE stockchief_runtime.job_events
  ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS job_events_sequence
  ON stockchief_runtime.job_events(seq);

DROP INDEX IF EXISTS stockchief_runtime.job_events_history;
CREATE INDEX job_events_history
  ON stockchief_runtime.job_events(job_id,seq);
